---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: AutoTest.6d3d1c06-acb2-419f-a7d9-6950a3734e8d.Boolean.Flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
