---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: AutoTest.a1ce2d08-f971-4d50-8b4e-9ffa40e68c64.Boolean.Flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
