---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: AutoTest.710a6dde-4b8d-469b-ba61-0a97ea7dc19c.Boolean.Flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
