---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: AutoTest.bcdfcc26-d121-4692-8b95-7111837f968b.Boolean.Flag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
