---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.06905141-3358-40e8-8dee-83932855fc64

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.67b44803-d33f-422a-8a03-15ff32f4241b.Boolean.Property
        operator: ne
        operands:
            - "false"
