---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.04d063f8-615d-4c32-a008-efdef4624bbb

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f7cab0c1-42af-444b-8368-6fb65b49cd09.Boolean.Property
        operator: ne
        operands:
            - "false"
