---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d918a8e3-5195-41dc-b855-cae4d5775cf5

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.3c034c68-b51e-447b-892e-fb33af133e5e.Boolean.Property
        operator: ne
        operands:
            - "false"
