---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.16a008ec-b185-4b9f-9c41-d682f3e396f2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.1d2710cb-93de-4832-9b7f-e28ece362723.Boolean.Property
        operator: ne
        operands:
            - "false"
