---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.60ca136e-f3dc-4b41-8e19-4e37fb789cef

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.a5aac896-d3db-41de-9db2-4f37d0e06580.Boolean.Property
        operator: ne
        operands:
            - "false"
