---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.414700e0-9ba0-4fe4-be86-7f2e698fa644

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9ddddae2-b597-47c1-b005-e815101ae1ee.Boolean.Property
        operator: ne
        operands:
            - "false"
