---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b811e74a-4291-4c95-8681-bc0ae2a8938e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.daebabca-534c-45f0-a3b1-c7bd5d65ee67.Boolean.Property
        operator: ne
        operands:
            - "false"
