---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.28653978-229a-4e11-a135-2b52ef0eca20

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9d19265f-e0e0-45ca-bace-f7089ada11bb.Boolean.Property
        operator: ne
        operands:
            - "false"
