---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.8c2a1693-eb8d-45ef-b814-5bcca318d947

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e0ab2bac-8cfa-48ab-9687-76aa54f46327.Boolean.Property
        operator: ne
        operands:
            - "false"
