---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.1c8c766b-a279-4d06-bf20-f832ccd84be5

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.5071bd68-0273-4a94-894b-c903911a14e0.Boolean.Property
        operator: ne
        operands:
            - "false"
