---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.da03afc3-054a-4d2e-a254-d4db1ebcab29

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d57f6f14-565a-41ee-8224-1be9c3df7329.Boolean.Property
        operator: ne
        operands:
            - "false"
