---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.32bf7d08-a2c8-4435-8031-98fb37031b82

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d3fe8bf4-78e1-48ef-a2dc-a47aa4b2c928.Boolean.Property
        operator: ne
        operands:
            - "false"
