---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.0876a8c5-171f-49f9-9895-0b3e1df5da97

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.1d887fca-c72f-4a59-9bf5-f57c479b36a9.Boolean.Property
        operator: ne
        operands:
            - "false"
