---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f58c8e64-d8d6-4017-a6f6-b537851f60d5

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.34092bc3-7e53-435c-94cb-777442ddb980.Boolean.Property
        operator: ne
        operands:
            - "false"
