---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.4482d5c2-519c-4c88-b304-3ff078bc21e3

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.530c12f9-fa83-4788-9058-a6699d52a625.Boolean.Property
        operator: ne
        operands:
            - "false"
