---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.9c1b726d-cc3e-41fb-95ff-0fbf7b843123

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.97690194-ead1-4e03-b3ff-69511644b09d.Boolean.Property
        operator: ne
        operands:
            - "false"
