---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.96f7c212-1fc3-4e40-9503-72a59ece0a0d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.768ab6b7-e1d9-4a89-acc1-ecca48550842.Boolean.Property
        operator: ne
        operands:
            - "false"
