---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.62037985-4135-41e4-9363-4ef361c12887

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.54095aea-930d-4dc4-9b9a-086893dac379.Boolean.Property
        operator: ne
        operands:
            - "false"
