---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.efeeae15-e643-4e10-8781-23686ee3f21b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.53b07e44-facc-477d-9b69-8bd3a9c6e0dc.Boolean.Property
        operator: ne
        operands:
            - "false"
