---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b334d195-48a0-4e56-8a87-c975fa86db2b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d76f6ce5-6556-4c46-bd7b-c2fa6e836518.Boolean.Property
        operator: ne
        operands:
            - "false"
