---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.0b8555dd-45f2-40de-ad6d-6163df050abd

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.5aef8f23-a3c8-4cd9-8bf9-cdc0fab064af.Boolean.Property
        operator: ne
        operands:
            - "false"
