---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f2751692-936a-4ad7-9c8d-9bd3f3c2643e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bf9050f7-2d28-4af8-8ab2-c0ac6605b6ec.Boolean.Property
        operator: ne
        operands:
            - "false"
