---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.20664045-757a-4184-8b3e-76a33418b74b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6cbc8d97-2aa3-472b-b165-608e35b5ebab.Boolean.Property
        operator: ne
        operands:
            - "false"
