---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2915b9a0-684a-401d-9046-c696f1528cf2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.4fce89fd-7748-4fb0-b502-084e0a9929b5.Boolean.Property
        operator: ne
        operands:
            - "false"
