---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3754a22d-0113-45ad-9b94-e36d36e02790

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e1e25368-3d46-4790-8f0c-36cf50694008.Boolean.Property
        operator: ne
        operands:
            - "false"
