---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.602b8bbb-5460-4b66-8a68-e86d8fa4139b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.1a403cb4-1c43-4691-8e38-0dd39b5d1145.Boolean.Property
        operator: ne
        operands:
            - "false"
