---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.4bbc3be9-b657-4bff-bd9d-62eb25f40f94

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.982b83fc-d370-40ac-a3db-32dcd70ce188.Boolean.Property
        operator: ne
        operands:
            - "false"
