---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.59f0d3ff-39a2-4eab-a8f4-57d819b442dc

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f2ea7571-32b2-421c-bfa1-aac2a5f8d8fe.Boolean.Property
        operator: ne
        operands:
            - "false"
