---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.0081b6ca-04a7-4f28-90f6-05b5c92424e6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.c4ee2f93-b99e-4c1c-8b23-0d4ee8eeadf4.Boolean.Property
        operator: ne
        operands:
            - "false"
