---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.934944a5-bc03-4aa7-989e-a3e1cdbea7ae

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ccdd43a5-8f67-4ad3-98fe-21416b248ff9.Boolean.Property
        operator: ne
        operands:
            - "false"
