---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.242f289f-c9a5-4daa-9a68-af2909a5c25d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f5f048b9-18a4-48e1-8fcf-5b788328e681.Boolean.Property
        operator: ne
        operands:
            - "false"
