---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.337b25a3-4602-4ff1-a2c9-2105fcaf796f

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.800815af-61dc-4178-82d8-f786c59e9d6b.Boolean.Property
        operator: ne
        operands:
            - "false"
