---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.cb02646a-7146-4255-b667-736f6d247c3b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.461283c2-73e4-4d6f-baa7-91b16817d5f4.Boolean.Property
        operator: ne
        operands:
            - "false"
