---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.bea0986a-8459-42e4-aae5-be55da3a4a57

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8e821630-b752-49a7-afee-51846f62ee8b.Boolean.Property
        operator: ne
        operands:
            - "false"
