---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.46b250b4-57f3-4bb5-9446-4991b37e2b15

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bca79227-3cb2-4962-bfcc-ec960aa6ea86.Boolean.Property
        operator: ne
        operands:
            - "false"
