---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f99be790-427f-461b-892e-20227a7c3d2e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d430d072-f155-49f8-9d4c-b7ca90c74ad4.Boolean.Property
        operator: ne
        operands:
            - "false"
