---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f1ead371-7dae-4037-9257-70806f77fbde

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2f84ef34-af06-4463-b499-cd70a5ce3057.Boolean.Property
        operator: ne
        operands:
            - "false"
