---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d71fed65-a9c7-4126-af03-914d6d51fecf

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.af780dcc-0266-44ce-a3b1-1cc0ae301e6e.Boolean.Property
        operator: ne
        operands:
            - "false"
