---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.36f9f0cd-da35-4d41-9d73-b1b4815b9d40

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e822cc52-f453-41b9-aaed-9da57e5e5c8a.Boolean.Property
        operator: ne
        operands:
            - "false"
