---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.8ee08c5b-decd-4413-a97a-f93c2f540ab0

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.b4685093-0f78-4f63-87d7-bab35c1384ee.Boolean.Property
        operator: ne
        operands:
            - "false"
