---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.add8483b-9a8d-4ced-b604-67fc787bf564

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6607a202-27fb-464b-8abe-2de9d191ed5f.Boolean.Property
        operator: ne
        operands:
            - "false"
