---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.7646b46a-040f-48eb-b71e-27e96b03e923

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f1150371-c3f8-4b20-82c5-28e223745719.Boolean.Property
        operator: ne
        operands:
            - "false"
