---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.82b9a2f0-bf44-460c-a5bf-fcc6fa1f5460

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bb28cd7b-56d5-4372-8b6c-6a9e395ce569.Boolean.Property
        operator: ne
        operands:
            - "false"
