---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.1cfef78b-db2b-41e4-9745-20dd5832eb19

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.164b183b-f913-4447-a9fc-0ad54756c82e.Boolean.Property
        operator: ne
        operands:
            - "false"
