---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.30bd98ec-8cc7-4c59-8519-b5d4f5159cfe

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.37cec7e7-a55e-47b8-b76e-bf3250e1807a.Boolean.Property
        operator: ne
        operands:
            - "false"
