---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2b9409cc-302c-470d-8456-a83d8b6f682b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.16fe4f4d-f466-4630-9406-a2a38664d1a6.Boolean.Property
        operator: ne
        operands:
            - "false"
