---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.4398b64a-d2a4-41eb-a21b-86ce526e2f22

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8acca9f5-cfea-4e7f-abb5-04a6853c28d6.Boolean.Property
        operator: ne
        operands:
            - "false"
