---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c0c26125-79a2-4404-af41-c1b4666d7750

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.4662409f-b84d-44de-9cc8-4d7c7c6daed6.Boolean.Property
        operator: ne
        operands:
            - "false"
