---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.1505651f-c116-4d50-aacf-3712396941c6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2c9e85a1-44a7-4deb-9fda-bad1fdc7cae1.Boolean.Property
        operator: ne
        operands:
            - "false"
