---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f318b5c5-dbcb-411d-a1a5-1a704d856448

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.dcff9598-7278-4ff5-9db7-caf407d48af6.Boolean.Property
        operator: ne
        operands:
            - "false"
