---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.cb776b96-47be-475f-bf4e-6423e8754ee8

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.802d0156-7596-497d-9195-ad6f52ae48ae.Boolean.Property
        operator: ne
        operands:
            - "false"
