---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.23ba7d29-05d3-48d0-87d6-a7e4b59ec2c9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.325c6d91-7802-407b-8e10-6527fe20c016.Boolean.Property
        operator: ne
        operands:
            - "false"
