---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.8033ce55-5940-4911-81fa-df1430cb1d5e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9459851e-bfbe-402d-87ee-1aebe464b982.Boolean.Property
        operator: ne
        operands:
            - "false"
