---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b4daa5c8-0208-4705-aa27-7802a5984c14

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.dcc75a68-5530-4cce-996f-6258bb916787.Boolean.Property
        operator: ne
        operands:
            - "false"
