---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2f867b3f-b403-447b-a1ad-1dab5032147a

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8ff6d6ac-04d3-45b2-88e1-35bd7cf2bd04.Boolean.Property
        operator: ne
        operands:
            - "false"
