---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.78a37f82-78d9-4558-859e-6b403dff8f8b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6c606ad9-f0c4-4464-9729-336b6abcba00.Boolean.Property
        operator: ne
        operands:
            - "false"
