---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e2a4a488-c8b3-4a97-a870-165c60fc71e5

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2b53e63c-491e-4616-a8a6-18d004a27f10.Boolean.Property
        operator: ne
        operands:
            - "false"
