---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.437ab0f4-f3d5-408a-ac72-acb0a100feb3

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ad9f519b-58bf-45ac-a73d-19c47e7eb8eb.Boolean.Property
        operator: ne
        operands:
            - "false"
