---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.75fcd72e-9c39-44a1-9fc6-01658be62994

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.69396bd4-c61f-4a72-9359-36775c71979e.Boolean.Property
        operator: ne
        operands:
            - "false"
