---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f94e9e21-11fd-425d-be2d-d7a421c02392

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2afb09c6-e08e-4d43-99a6-a46e430664ab.Boolean.Property
        operator: ne
        operands:
            - "false"
