---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3a56c099-0395-4b5b-9944-f266ec44dc61

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.edcc4a6f-d5de-4156-a324-dbb67cfd6e97.Boolean.Property
        operator: ne
        operands:
            - "false"
