---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.ff41056c-4d4f-48ec-a023-6eddb0f79590

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9bbadda1-c208-44a1-bda2-6387d2ac7622.Boolean.Property
        operator: ne
        operands:
            - "false"
