---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.5f7c2cb0-3d58-4f10-9d60-7ba7a3bffd40

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d9a7d8ea-680d-4052-8196-2382e39c65bc.Boolean.Property
        operator: ne
        operands:
            - "false"
