---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.26f04389-7d04-4f72-bf02-ab3702a25623

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.208a9bfe-04c1-40eb-9c31-f91ca7e1ba6e.Boolean.Property
        operator: ne
        operands:
            - "false"
