---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.762c69d4-f0f6-45f6-bbfa-6fb11011101a

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bb89ccbf-42f7-4505-ac9e-8e32526a46b9.Boolean.Property
        operator: ne
        operands:
            - "false"
