---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.7e39d6b1-8868-4474-8b3d-e00d72aad6f8

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.02cb88a0-3669-45f4-ac26-8d781bc34558.Boolean.Property
        operator: ne
        operands:
            - "false"
