---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.9659d919-891e-42ab-8f1d-8e7a4b38773e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.088b3fb6-0f88-4544-ac1e-1822d1f1ad31.Boolean.Property
        operator: ne
        operands:
            - "false"
