---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.caa7390b-b30e-4553-b0f0-f9ca8641ddce

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.754fe9da-352b-4a8b-af17-211139519796.Boolean.Property
        operator: ne
        operands:
            - "false"
