---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d362e534-0486-4ea9-8120-e3a45a92f046

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6f1e3b35-2348-4020-b70e-7bf2f7647317.Boolean.Property
        operator: ne
        operands:
            - "false"
