---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.35741514-1198-4771-9258-b0d156a3ee89

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d336a74c-de5a-4b1c-ad58-6f25111ed78b.Boolean.Property
        operator: ne
        operands:
            - "false"
