---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.7c4ee542-0b3e-4bad-891b-0890df2193e9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.14f3a7b6-4225-4e2b-afb2-1d96e2cf503d.Boolean.Property
        operator: ne
        operands:
            - "false"
