---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.25088b96-75d9-4de9-b342-c8b942dda877

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e560074b-849b-4ad4-848c-71ba185dd71b.Boolean.Property
        operator: ne
        operands:
            - "false"
