---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.723952d3-9e92-44af-a0ac-a2263e0ab161

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.00655b17-2b22-4b65-8c59-e153498db9b9.Boolean.Property
        operator: ne
        operands:
            - "false"
