---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.9f7c5430-2943-4a59-8433-dec98e86bff2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e51342ec-803c-48cc-afda-e4d3c82273f5.Boolean.Property
        operator: ne
        operands:
            - "false"
