---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d02d3c1d-7897-41b9-beee-949432a5ebc2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.fdda65f0-2dce-4420-8057-e925c318ec4a.Boolean.Property
        operator: ne
        operands:
            - "false"
