---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.40a0699e-eb51-4315-8858-edea250c9ca4

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8512a705-bfa5-4f66-a616-a45d111de020.Boolean.Property
        operator: ne
        operands:
            - "false"
