---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f5645666-f6cd-46c9-a2d1-92dbbc4fa6e9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.5343d7bf-6c81-4a93-a273-8e00a434f0bc.Boolean.Property
        operator: ne
        operands:
            - "false"
