---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.36ca40e2-b9a4-49d3-9ec9-0573f1fb6bef

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.07bfe34d-848c-47c0-9dea-ef852757c886.Boolean.Property
        operator: ne
        operands:
            - "false"
