---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2f33ecbf-2316-4f2d-8aa1-e4d6ee2514e4

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.3857d3c6-ce76-4584-9807-62dfd5b5147c.Boolean.Property
        operator: ne
        operands:
            - "false"
