---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f6025c1f-cff9-4714-ad09-a7896ef2861d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9078f166-c9f4-4bf5-a4b4-cda52d6415ba.Boolean.Property
        operator: ne
        operands:
            - "false"
