---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.dfa9e6ba-a6fe-46b7-a44f-3f1344af62c9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.5cbef909-e03e-41b7-b0ea-9f0ea69bf11f.Boolean.Property
        operator: ne
        operands:
            - "false"
