---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.49edb359-22a2-42bc-ada4-e10046a3f115

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.3c1a3493-017a-4d72-869f-3c3b90311b01.Boolean.Property
        operator: ne
        operands:
            - "false"
