---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.794a9136-9fd6-43e0-8086-2400391ae8e6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.fc1f4468-9146-4842-9f2e-04476d61bb98.Boolean.Property
        operator: ne
        operands:
            - "false"
