---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3e9183bd-3bd9-4132-af0f-1a5ec1cbb486

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2e4cdeed-f742-4ac1-b775-6e5b4e91f02b.Boolean.Property
        operator: ne
        operands:
            - "false"
