---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.77e33b8e-68f1-44b1-b665-73a474c787c2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.208c46fe-01c4-43bd-bccb-531c9ddeae7b.Boolean.Property
        operator: ne
        operands:
            - "false"
