---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f0ff4eca-d7b4-4f2c-a510-20d7f51873d1

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.c3b24f8b-ecd3-4c19-9758-2e0ff25ab8d7.Boolean.Property
        operator: ne
        operands:
            - "false"
