---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.980efd99-7bc5-4ad2-acab-9b1781f6cc73

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ebd6a279-27af-444f-9a35-8a9773cebbc0.Boolean.Property
        operator: ne
        operands:
            - "false"
