---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b4b41bb2-efa7-4ae4-89fd-7f45e688b0ec

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8db70c51-adca-4b4e-bdb8-ca1c300dc792.Boolean.Property
        operator: ne
        operands:
            - "false"
