---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.67884c9e-7aa9-4b4c-aa2a-b8d337ac1c32

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8e5ced01-a755-4bfc-ab7b-1988a82619f6.Boolean.Property
        operator: ne
        operands:
            - "false"
