---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e7422c4a-c34e-478a-9d2d-e155175aa3bc

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e391877a-3865-4262-8c41-7d227ddf881c.Boolean.Property
        operator: ne
        operands:
            - "false"
