---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3694b75b-7c1f-43e9-99be-bc1560bfe7e7

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.da2c6e1a-a835-4e9b-ac7d-d795d919a054.Boolean.Property
        operator: ne
        operands:
            - "false"
