---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b5c335bb-9654-4876-98f6-e1d3702cacd0

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f5939ed7-f097-4d14-bca8-a119522bccd9.Boolean.Property
        operator: ne
        operands:
            - "false"
