---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e17d1da2-ef5c-4612-98bf-fbf8ee3ee60d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0b7290b5-bd8c-498c-bf0d-68cc3c2e1333.Boolean.Property
        operator: ne
        operands:
            - "false"
