---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2d943ceb-15b4-4ca9-a386-c5401488955a

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.fe4625f2-0cd6-46ce-abd2-bcb022fcd24d.Boolean.Property
        operator: ne
        operands:
            - "false"
