---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.aa821643-f7a4-4e11-b4c8-677fdadba559

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.735e8834-0184-4e8f-92fe-83f7732783a7.Boolean.Property
        operator: ne
        operands:
            - "false"
