---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.ad529e6e-55c3-459e-b76e-dbb7c5911a34

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8ee5e7e7-5e95-4e36-ab9f-3aedb959e4f1.Boolean.Property
        operator: ne
        operands:
            - "false"
