---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.a3f9a147-9a4b-4166-8769-9ab32ed96325

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0eee855a-e397-4f56-9738-0713988f292e.Boolean.Property
        operator: ne
        operands:
            - "false"
