---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c60b3b99-2aa7-4ddc-a40f-f827b10c8da7

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ed8b5952-6a18-48d4-b9a7-48a09a1b176c.Boolean.Property
        operator: ne
        operands:
            - "false"
