---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b6496e42-d9ae-47f4-bddb-e9debe3b32dc

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.a69325b6-dfbe-4816-922a-91a31e5c19cd.Boolean.Property
        operator: ne
        operands:
            - "false"
