---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2c8e0150-0c68-48e7-b15c-226498edcbb9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2ef9d2b8-6541-4212-8775-c9e80cbaefea.Boolean.Property
        operator: ne
        operands:
            - "false"
