---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.ac043e9a-0893-44a2-acf2-072efdd59149

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.dbe27a9a-3279-4220-8f00-402145de6171.Boolean.Property
        operator: ne
        operands:
            - "false"
