---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2007a3f2-846b-47e1-b49f-04ba5a31b5e0

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f2015ea7-6e6d-467a-9269-e8a8c7407b2f.Boolean.Property
        operator: ne
        operands:
            - "false"
