---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.61df9570-b1ba-4a26-abdb-c90b251f5c2d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.e87115d2-c9bf-41dc-aef6-b54502cd0726.Boolean.Property
        operator: ne
        operands:
            - "false"
