---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.cd4d7af3-f6dd-49ad-8f99-eab392bcac5a

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.55455712-4222-4ef7-975f-8f900b7b918b.Boolean.Property
        operator: ne
        operands:
            - "false"
