---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.42107e61-ee0f-4961-ab62-cec2856e50a1

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.8f30f629-4886-45d4-b289-1607d627425c.Boolean.Property
        operator: ne
        operands:
            - "false"
