---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3d38be0f-731c-4792-b770-1f377ea60c45

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.261f0940-03ad-480b-b4f0-4ab1b81235d3.Boolean.Property
        operator: ne
        operands:
            - "false"
