---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e5bbf623-dc54-4c71-b4bc-5f178889e9d6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.3c8d3057-298d-4c94-bd1d-ee04c3aafcd2.Boolean.Property
        operator: ne
        operands:
            - "false"
