---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c025681f-729b-4cf2-b954-6012b97eb73f

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.749e89de-b2bd-4b3d-957c-d07f07165923.Boolean.Property
        operator: ne
        operands:
            - "false"
