---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3db328ef-7306-444d-8224-c1dcf26ba9c6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.2f751121-8071-465b-8956-f74f10978133.Boolean.Property
        operator: ne
        operands:
            - "false"
