---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.c78124b1-c553-40c7-88a0-1a960b5634b9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.a53e7384-ed07-4714-847d-e45cbae9a3d1.Boolean.Property
        operator: ne
        operands:
            - "false"
