---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.51e6e591-6c47-4643-a8f0-bc8ad3bcaddb

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.f0d429f3-1afa-4e4e-aa24-2e0c842e7384.Boolean.Property
        operator: ne
        operands:
            - "false"
