---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.8166c980-2fd1-4cc8-ac28-64f897460085

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.d8f1422e-73fc-4061-802e-36c13f89ad0f.Boolean.Property
        operator: ne
        operands:
            - "false"
