---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.6cdf8ea6-bcc1-43b3-81cc-683d82d20bd2

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.89ae849c-5e51-4d45-9c22-6f724ff34665.Boolean.Property
        operator: ne
        operands:
            - "false"
