---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.bd743d1f-a381-4b1c-83e1-711779fe539b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.084d4910-ae2b-4c42-96d8-ef4e33fae8a7.Boolean.Property
        operator: ne
        operands:
            - "false"
