---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.d6c5944c-343e-45e1-9dd9-ece7798c3f04

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.0b4affd3-78ab-4faa-b3c4-a65da97e8f62
        operator: ne
        operands:
            - "false"
