---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.285b8d9a-29b4-4e88-9391-d0b94b6d495b

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.9cabef5c-d8c0-4873-924d-95ef4dd04efd
        operator: ne
        operands:
            - "false"
