---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.66ac8a24-55f5-4bcd-b916-341ac534d5d8

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.3f1888fb-83da-4204-b36e-a0011f3010fd
        operator: ne
        operands:
            - "false"
