---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.196c6bf7-0eb1-488c-819b-d21d1a1b3e44

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.493acd3b-0e9b-4688-a8e2-875331de4ab5
        operator: ne
        operands:
            - "false"
