---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.25575258-e59b-4f94-99c9-4172e0774378

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.cbc4bf82-2467-4da1-bd9e-ea204cd70f47
        operator: ne
        operands:
            - "false"
