---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.da175063-94c6-4691-8ef1-4a7723e33cdb

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.4b5daa23-e512-4145-9fe6-11207688d453
        operator: ne
        operands:
            - "false"
