---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.d2f7a981-730e-44d4-ae26-00115418ba55

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.cd08ece9-746f-4af8-998a-84b15b57d525
        operator: ne
        operands:
            - "false"
