---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.e0ec5c5a-2b91-40e9-b8d6-8c270dc4cb50

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.1d2b46eb-5182-4d41-9709-7a2cf061bad4
        operator: ne
        operands:
            - "false"
