---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.61337322-13f7-4330-ad42-40c7e1d10d72

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.5c77cb31-9813-4318-8d7b-64088c155eda
        operator: ne
        operands:
            - "false"
