---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.cf583806-bb40-465d-9206-fa3ce60a47f8

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.ddb24466-97bd-4843-adab-978e4c2c0a5a
        operator: ne
        operands:
            - "false"
