---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.fb8f365a-49cc-438f-8b8a-596dfc28986c

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.accd8a4b-ff66-4f31-ad42-7cd05eb92353
        operator: ne
        operands:
            - "false"
