---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.b49fc092-dc85-4f27-b86d-84d4bb3dbc8f

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.2c16a858-e1cc-4ca9-a364-62785ad23089
        operator: ne
        operands:
            - "false"
