---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.82dd3127-08dd-482d-ac30-bb6f01651eeb

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.399726c9-9421-4969-bdd5-81e7a88e6e12
        operator: ne
        operands:
            - "false"
