---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AutoTest.930cea3b-411b-4f63-8606-ac9bd53b27fb.Boolean.Flag
flagType: boolean
description: AutoTest Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
