---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AutoTest.5a3484ae-28ba-4110-8905-d002ea4fceb3.Boolean.Flag
flagType: boolean
description: AutoTest Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
