---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AutoTest.dcfef381-6025-4bfe-926a-833b9a145410.Boolean.Flag
flagType: boolean
description: AutoTest Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
