---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AutoTest.2b39f1ad-250e-4cf3-b908-0d835f174c73.Boolean.Flag
flagType: boolean
description: AutoTest Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
