---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AutoTest.d3accba2-1c38-4bbd-a90a-91c4ca699d69.Boolean.Flag
flagType: boolean
description: AutoTest Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
